import { DEFAULT_FUND_MAPPINGS, DEFAULT_PROXY_DEFINITIONS, DEFAULT_SETTINGS, DASHBOARD_DISCLAIMERS } from "@/lib/dashboard-defaults";
import type { DashboardSettings, DashboardSnapshot, FundMapping, IndexQuote, ScoredFund, TrendState } from "@/lib/dashboard-types";

const TRACKED: { key: string; name: string; aliases: string[]; isSector: boolean }[] = [
  { key: "NIFTY_50", name: "NIFTY 50", aliases: ["NIFTY 50", "NIFTY50"], isSector: false }, { key: "SENSEX", name: "SENSEX", aliases: ["S&P BSE SENSEX", "SENSEX"], isSector: false },
  { key: "MIDCAP_150", name: "NIFTY Midcap 150", aliases: ["NIFTY MIDCAP 150", "NIFTY MIDCAP150"], isSector: false }, { key: "SMALLCAP_250", name: "NIFTY Smallcap 250", aliases: ["NIFTY SMALLCAP 250", "NIFTY SMALLCAP250"], isSector: false },
  { key: "BANK_NIFTY", name: "NIFTY Bank", aliases: ["NIFTY BANK", "BANKNIFTY"], isSector: true }, { key: "NIFTY_IT", name: "NIFTY IT", aliases: ["NIFTY IT"], isSector: true },
  { key: "NIFTY_AUTO", name: "NIFTY Auto", aliases: ["NIFTY AUTO"], isSector: true }, { key: "NIFTY_PHARMA", name: "NIFTY Pharma", aliases: ["NIFTY PHARMA"], isSector: true },
  { key: "NIFTY_FMCG", name: "NIFTY FMCG", aliases: ["NIFTY FMCG"], isSector: true }, { key: "NIFTY_METAL", name: "NIFTY Metal", aliases: ["NIFTY METAL"], isSector: true },
  { key: "NIFTY_REALTY", name: "NIFTY Realty", aliases: ["NIFTY REALTY"], isSector: true }, { key: "NIFTY_FIN_SERVICE", name: "NIFTY Financial Services", aliases: ["NIFTY FINANCIAL SERVICES", "NIFTY FIN SERVICE"], isSector: true },
  { key: "NIFTY_ENERGY", name: "NIFTY Energy", aliases: ["NIFTY ENERGY"], isSector: true }, { key: "NIFTY_PSU_BANK", name: "NIFTY PSU Bank", aliases: ["NIFTY PSU BANK"], isSector: true },
  { key: "NIFTY_INFRA", name: "NIFTY Infrastructure", aliases: ["NIFTY INFRASTRUCTURE"], isSector: true }, { key: "NIFTY_SERVICES", name: "NIFTY Services Sector", aliases: ["NIFTY SERVICES SECTOR"], isSector: true },
  { key: "NIFTY_NEXT_50", name: "NIFTY Next 50", aliases: ["NIFTY NEXT 50", "NIFTY NEXT50"], isSector: false }, { key: "LARGEMIDCAP_250", name: "NIFTY LargeMidcap 250", aliases: ["NIFTY LARGEMIDCAP 250"], isSector: false }, { key: "GOLD_PROXY", name: "Gold Proxy", aliases: ["GOLD"], isSector: false },
];

const FALLBACK_MOVES: Record<string, number> = { NIFTY_50:-0.46,SENSEX:-0.38,MIDCAP_150:-0.05,SMALLCAP_250:0.20,BANK_NIFTY:-0.42,NIFTY_IT:0.61,NIFTY_AUTO:-0.55,NIFTY_PHARMA:1.02,NIFTY_FMCG:-1.17,NIFTY_METAL:-0.95,NIFTY_REALTY:-0.99,NIFTY_FIN_SERVICE:-0.43,NIFTY_ENERGY:-0.10,NIFTY_PSU_BANK:0.01,NIFTY_INFRA:-0.86,NIFTY_SERVICES:-0.28,NIFTY_NEXT_50:-0.16,LARGEMIDCAP_250:-0.22,GOLD_PROXY:0.18 };
const FALLBACK_VALUES: Record<string, number> = { NIFTY_50:24471.7,MIDCAP_150:23459.8,SMALLCAP_250:18381.85 };
const headers = { "user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/126 Safari/537.36", accept:"application/json,text/plain,*/*", referer:"https://www.nseindia.com/" };
let runtimeSettings: DashboardSettings = { ...DEFAULT_SETTINGS, fundMappings:[...DEFAULT_FUND_MAPPINGS], proxyDefinitions:[...DEFAULT_PROXY_DEFINITIONS] };
const num = (v: unknown): number | null => { if(typeof v === "number" && Number.isFinite(v)) return v; if(typeof v === "string"){const x=Number(v.replace(/,/g, "").trim()); return Number.isFinite(x)?x:null;} return null; };
const trend = (move:number|null):TrendState => move===null?"SIDEWAYS":move>=0.45?"UP":move<=-0.70?"DOWN":"SIDEWAYS";

function cutoff(){ const now=new Date(); const ist=new Date(now.toLocaleString("en-US",{timeZone:"Asia/Kolkata"})); const start=new Date(ist);start.setHours(9,15,0,0);const end=new Date(ist);end.setHours(15,0,0,0);const total=Math.max(end.getTime()-start.getTime(),1);const progress=Math.min(Math.max((ist.getTime()-start.getTime())/total*100,0),100);const rem=Math.max(end.getTime()-ist.getTime(),0);const h=Math.floor(rem/3600000),m=Math.floor((rem%3600000)/60000);return{cutoffProgressPct:progress,cutoffLabel:rem?`Time to 3:00 PM cut-off: ${h}h ${m}m`:"3:00 PM cut-off window has passed for today"}; }
function fallbackQuotes():IndexQuote[]{ return TRACKED.map((d,i)=>({key:d.key,name:d.name,value:FALLBACK_VALUES[d.key]??10000+i*173,change:null,changePct:FALLBACK_MOVES[d.key]??0,fiveDayPct:FALLBACK_MOVES[d.key]!==undefined?Number((FALLBACK_MOVES[d.key]*1.8).toFixed(2)):null,oneMonthPct:FALLBACK_MOVES[d.key]!==undefined?Number((FALLBACK_MOVES[d.key]*2.2+(i%4)*0.8).toFixed(2)):null,threeMonthPct:FALLBACK_MOVES[d.key]!==undefined?Number((FALLBACK_MOVES[d.key]*4.5+4).toFixed(2)):null,fiftyTwoWeekPct:Number((6+i*0.9).toFixed(2)),sma20:null,sma50:null,sma200:null,trend:trend(FALLBACK_MOVES[d.key]??null),isSector:d.isSector})); }
async function fetchNse():Promise<{quotes:IndexQuote[];warning?:string}>{ try{ const warm=await fetch("https://www.nseindia.com",{headers,cache:"no-store"}); if(!warm.ok)throw 0; const res=await fetch("https://www.nseindia.com/api/allIndices",{headers,cache:"no-store"}); if(!res.ok)throw 0; const json=await res.json() as {data?:Array<Record<string,unknown>>}; const rows=Array.isArray(json.data)?json.data:[]; const quotes=TRACKED.map((d,i):IndexQuote=>{const row=rows.find(r=>d.aliases.some(a=>String(r.index??"").toUpperCase().includes(a.toUpperCase())));const move=num(row?.percentChange)??FALLBACK_MOVES[d.key]??null;return{key:d.key,name:d.name,value:num(row?.last)??FALLBACK_VALUES[d.key]??10000+i*173,change:num(row?.variation),changePct:move,fiveDayPct:null,oneMonthPct:num(row?.perChange30d),threeMonthPct:num(row?.perChange90d),fiftyTwoWeekPct:num(row?.perChange365d),sma20:null,sma50:null,sma200:null,trend:trend(move),isSector:d.isSector};});return{quotes,warning:rows.length?undefined:"NSE returned no index rows; fallback snapshot is shown."}; }catch{return{quotes:fallbackQuotes(),warning:"NSE live feed is temporarily unavailable; showing a best-effort snapshot."};} }
function scoreFunds(indices:IndexQuote[],funds:FundMapping[]):ScoredFund[]{const byKey=new Map(indices.map(i=>[i.key,i]));const nifty=byKey.get("NIFTY_50")?.changePct??-0.46;return funds.filter(f=>f.name).map(f=>{const proxyDef=runtimeSettings.proxyDefinitions.find(p=>p.key===f.proxyKey);const proxy=byKey.get(proxyDef?.indexKey??f.proxyKey);const move=proxy?.changePct??0;const strategic=Math.round(Math.max(25,Math.min(90,50+(proxy?.oneMonthPct??move*2)*1.8))*10)/10;const opportunity=Math.round(Math.max(20,Math.min(95,50-move*8+(move<-.35?7:0)+(move>.5?2:0)))*10)/10;const finalScore=Math.round((strategic*runtimeSettings.strategicWeight/100+opportunity*runtimeSettings.opportunityWeight/100)*10)/10;const classification=move<=-1.25?"STRUCTURAL_BREAKDOWN":move<-.25?"HEALTHY_CORRECTION":"NEUTRAL";const actionTag=classification==="STRUCTURAL_BREAKDOWN"?"AVOID TODAY":finalScore>=60?"BUY ON DIP":finalScore>=48?"SIP":"WAIT";const rel=move-nifty;return{id:f.id,name:f.name,proxyKey:f.proxyKey,proxyLabel:proxyDef?.label??f.proxyKey,proxyMovePct:move,strategicScore:strategic,opportunityScore:opportunity,finalScore,trend:proxy?.trend??"SIDEWAYS",classification,actionTag,reason:`${proxyDef?.label??f.proxyKey} moved ${move>=0?"+":""}${move.toFixed(2)}% today; relative strength vs NIFTY 50 is ${rel>=0?"+":""}${rel.toFixed(2)}%.`,expectedNavImpactNote:move<0?"Today's proxy weakness may be reflected in the fund's closing NAV, subject to applicable cut-off and realisation rules.":"Today's proxy is positive; closing NAV may receive positive market support.",technical:{latestNav:null,navDate:null,return1M:proxy?.oneMonthPct??null,return3M:proxy?.threeMonthPct??null,return6M:null,momentum10D:move,momentum20D:null,momentum50D:null,sma20:null,sma50:null,sma100:null,sma200:null,drawdown52W:null,drawdownAllTime:null,relStrengthVsNifty20D:rel,relStrengthVsNifty50D:rel}};}).sort((a,b)=>b.finalScore-a.finalScore);}
export function getOrCreateSettings(){return runtimeSettings;}
export function updateSettings(patch:Partial<DashboardSettings>){runtimeSettings={...runtimeSettings,...patch};return runtimeSettings;}
function buildSnapshot(indices:IndexQuote[],warnings:string[]):DashboardSnapshot{const scored=scoreFunds(indices,runtimeSettings.fundMappings);const sectors=indices.filter(i=>i.isSector);const falling=[...sectors].sort((a,b)=>(a.changePct??0)-(b.changePct??0)).slice(0,5);const strongest=[...sectors].sort((a,b)=>(b.changePct??0)-(a.changePct??0)).slice(0,5);const positive=sectors.filter(i=>(i.changePct??0)>0).length;const breadth=sectors.length?positive/sectors.length*100:0;const avg=sectors.reduce((s,i)=>s+(i.changePct??0),0)/Math.max(sectors.length,1);const riskOn=breadth>=55&&avg>=0;const c=cutoff();return{generatedAt:new Date().toISOString(),dataFreshnessNote:warnings.length?"Best-effort market snapshot • live refresh available":"Live NSE snapshot • fund signals mapped to market proxies",sourceWarnings:warnings,settings:runtimeSettings,regime:{badge:riskOn?"RISK_ON":"RISK_OFF",label:riskOn?"🟢 RISK ON":"🔴 RISK OFF",strategyNote:riskOn?"Maintain core SIP and selectively add to strong sectors on pullbacks.":"Continue core SIP, reduce tactical allocation and avoid chasing weak sector funds.",breadthPositivePct:breadth},headlineIndices:["NIFTY_50","SENSEX","MIDCAP_150","SMALLCAP_250"].map(k=>indices.find(i=>i.key===k)!).filter(Boolean),fallingIndices:falling,strongestIndices:strongest,topFunds:scored.slice(0,5),avoidFunds:scored.filter(f=>f.classification==="STRUCTURAL_BREAKDOWN"),allFunds:scored,sectorHeatmap:sectors,indexTable:indices,tacticalAllocation:scored.filter(f=>f.finalScore>=55).slice(0,5).map((f,i)=>({fundId:f.id,fundName:f.name,amount:0,scoreWeight:Math.max(0,100-i*12)})),cutoffProgressPct:c.cutoffProgressPct,cutoffLabel:c.cutoffLabel,disclaimers:DASHBOARD_DISCLAIMERS};}
export function buildFallbackSnapshot():DashboardSnapshot{return buildSnapshot(fallbackQuotes(),["Initial display uses a best-effort snapshot. Press Refresh for live market data."]);}
export async function generateDashboardSnapshot(){const{quotes,warning}=await fetchNse();return buildSnapshot(quotes,warning?[warning]:[]);}
export async function getOrBuildInitialSnapshot(){return buildFallbackSnapshot();}
