import { DEFAULT_FUND_MAPPINGS, DEFAULT_PROXY_DEFINITIONS, DEFAULT_SETTINGS, DASHBOARD_DISCLAIMERS } from "@/lib/dashboard-defaults";
import type { DashboardSettings, DashboardSnapshot, FundActionTag, FundClassification, FundMapping, IndexQuote, ScoredFund, TrendState } from "@/lib/dashboard-types";

const TRACKED:{key:string;name:string;aliases:string[];isSector:boolean}[]=[
 {key:"NIFTY_50",name:"NIFTY 50",aliases:["NIFTY 50","NIFTY50"],isSector:false},{key:"SENSEX",name:"SENSEX",aliases:["S&P BSE SENSEX","SENSEX"],isSector:false},
 {key:"MIDCAP_150",name:"NIFTY Midcap 150",aliases:["NIFTY MIDCAP 150","NIFTY MIDCAP150"],isSector:false},{key:"SMALLCAP_250",name:"NIFTY Smallcap 250",aliases:["NIFTY SMALLCAP 250","NIFTY SMALLCAP250"],isSector:false},
 {key:"NIFTY_NEXT_50",name:"NIFTY Next 50",aliases:["NIFTY NEXT 50","NIFTY NEXT50"],isSector:false},{key:"LARGEMIDCAP_250",name:"NIFTY LargeMidcap 250",aliases:["NIFTY LARGEMIDCAP 250"],isSector:false},
 {key:"BANK_NIFTY",name:"NIFTY Bank",aliases:["NIFTY BANK","BANKNIFTY"],isSector:true},{key:"NIFTY_IT",name:"NIFTY IT",aliases:["NIFTY IT"],isSector:true},
 {key:"NIFTY_AUTO",name:"NIFTY Auto",aliases:["NIFTY AUTO"],isSector:true},{key:"NIFTY_PHARMA",name:"NIFTY Pharma",aliases:["NIFTY PHARMA"],isSector:true},
 {key:"NIFTY_FMCG",name:"NIFTY FMCG",aliases:["NIFTY FMCG"],isSector:true},{key:"NIFTY_METAL",name:"NIFTY Metal",aliases:["NIFTY METAL"],isSector:true},
 {key:"NIFTY_REALTY",name:"NIFTY Realty",aliases:["NIFTY REALTY"],isSector:true},{key:"NIFTY_FIN_SERVICE",name:"NIFTY Financial Services",aliases:["NIFTY FINANCIAL SERVICES","NIFTY FIN SERVICE"],isSector:true},
 {key:"NIFTY_ENERGY",name:"NIFTY Energy",aliases:["NIFTY ENERGY"],isSector:true},{key:"NIFTY_PSU_BANK",name:"NIFTY PSU Bank",aliases:["NIFTY PSU BANK"],isSector:true},
 {key:"NIFTY_INFRA",name:"NIFTY Infrastructure",aliases:["NIFTY INFRASTRUCTURE"],isSector:true},{key:"NIFTY_SERVICES",name:"NIFTY Services Sector",aliases:["NIFTY SERVICES SECTOR"],isSector:true},
 {key:"GOLD_PROXY",name:"Gold Proxy",aliases:["GOLD"],isSector:false}
];
const FALLBACK_MOVES:Record<string,number>={NIFTY_50:-0.46,SENSEX:-0.38,MIDCAP_150:-0.05,SMALLCAP_250:0.20,NIFTY_NEXT_50:-0.16,LARGEMIDCAP_250:-0.22,BANK_NIFTY:-0.42,NIFTY_IT:0.61,NIFTY_AUTO:-0.55,NIFTY_PHARMA:1.02,NIFTY_FMCG:-1.17,NIFTY_METAL:-0.95,NIFTY_REALTY:-0.99,NIFTY_FIN_SERVICE:-0.43,NIFTY_ENERGY:-0.10,NIFTY_PSU_BANK:0.01,NIFTY_INFRA:-0.86,NIFTY_SERVICES:-0.28,GOLD_PROXY:0.18};
const FALLBACK_VALUES:Record<string,number>={NIFTY_50:24471.7,SENSEX:10173,MIDCAP_150:23459.8,SMALLCAP_250:18381.85};
const NSE_HEADERS={"user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/126 Safari/537.36",accept:"application/json,text/plain,*/*",referer:"https://www.nseindia.com/"};
const YAHOO_SYMBOLS:Record<string,string>={NIFTY_50:"%5ENSEI",SENSEX:"%5EBSESN",MIDCAP_150:"NIFTYMIDCAP150.NS",SMALLCAP_250:"NIFTYSMLCAP250.NS",NIFTY_NEXT_50:"NIFTYNXT50.NS",LARGEMIDCAP_250:"NIFTY_LARGEMID250.NS",BANK_NIFTY:"%5ENSEBANK",NIFTY_IT:"%5ECNXIT",NIFTY_AUTO:"%5ECNXAUTO",NIFTY_PHARMA:"%5ECNXPHARMA",NIFTY_FMCG:"%5ECNXFMCG",NIFTY_METAL:"%5ECNXMETAL",NIFTY_REALTY:"%5ECNXREALTY",NIFTY_FIN_SERVICE:"NIFTYFINSERVICE.NS",NIFTY_ENERGY:"NIFTYENERGY.NS",NIFTY_PSU_BANK:"NIFTYPSUBANK.NS",NIFTY_INFRA:"NIFTYINFRA.NS",NIFTY_SERVICES:"NIFTYSERVICES.NS"};
let runtimeSettings:DashboardSettings={...DEFAULT_SETTINGS,fundMappings:[...DEFAULT_FUND_MAPPINGS],proxyDefinitions:[...DEFAULT_PROXY_DEFINITIONS]};
const num=(v:unknown):number|null=>{if(typeof v==="number"&&Number.isFinite(v))return v;if(typeof v==="string"){const x=Number(v.replace(/,/g,"").trim());return Number.isFinite(x)?x:null}return null};
const trend=(move:number|null):TrendState=>move===null?"SIDEWAYS":move>=0.45?"UP":move<=-0.70?"DOWN":"SIDEWAYS";
function cutoff(){const now=new Date();const ist=new Date(now.toLocaleString("en-US",{timeZone:"Asia/Kolkata"}));const start=new Date(ist);start.setHours(9,15,0,0);const end=new Date(ist);end.setHours(15,0,0,0);const total=Math.max(end.getTime()-start.getTime(),1);const progress=Math.min(Math.max((ist.getTime()-start.getTime())/total*100,0),100);const rem=Math.max(end.getTime()-ist.getTime(),0);const h=Math.floor(rem/3600000),m=Math.floor((rem%3600000)/60000);return{cutoffProgressPct:progress,cutoffLabel:rem?`Time to 3:00 PM cut-off: ${h}h ${m}m`:"3:00 PM cut-off window has passed for today",passed:rem===0}}
function fallbackQuotes():IndexQuote[]{return TRACKED.map((d,i)=>({key:d.key,name:d.name,value:FALLBACK_VALUES[d.key]??10000+i*173,change:null,changePct:FALLBACK_MOVES[d.key]??0,fiveDayPct:null,oneMonthPct:null,threeMonthPct:null,fiftyTwoWeekPct:null,sma20:null,sma50:null,sma200:null,trend:trend(FALLBACK_MOVES[d.key]??null),isSector:d.isSector}))}

async function fetchYahoo():Promise<{quotes:IndexQuote[];warning?:string}>{
 const results=await Promise.all(TRACKED.map(async d=>{const symbol=YAHOO_SYMBOLS[d.key];if(!symbol)return null;try{const res=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${symbol}?range=1y&interval=1d`,{cache:"no-store",headers:{accept:"application/json"}});if(!res.ok)return null;const json=await res.json() as any;const r=json?.chart?.result?.[0];const closes=(r?.indicators?.quote?.[0]?.close??[]).filter((v:unknown):v is number=>typeof v==="number"&&Number.isFinite(v));if(!r||!closes.length)return null;const value=num(r?.meta?.regularMarketPrice)??closes.at(-1)??null;const prev=num(r?.meta?.previousClose)??(closes.length>1?closes.at(-2)??null:null);const pct=value!==null&&prev?((value-prev)/prev)*100:null;const ret=(days:number)=>closes.length>days?((closes[closes.length-1]/closes[closes.length-days-1])-1)*100:null;return{key:d.key,name:d.name,value,change:value!==null&&prev!==null?value-prev:null,changePct:pct,fiveDayPct:ret(5),oneMonthPct:ret(21),threeMonthPct:ret(63),fiftyTwoWeekPct:ret(252),sma20:closes.length>=20?closes.slice(-20).reduce((a:number,b:number)=>a+b,0)/20:null,sma50:closes.length>=50?closes.slice(-50).reduce((a:number,b:number)=>a+b,0)/50:null,sma200:closes.length>=200?closes.slice(-200).reduce((a:number,b:number)=>a+b,0)/200:null,trend:trend(pct),isSector:d.isSector} as IndexQuote}catch{return null}}));
 const quotes=TRACKED.map((d,i)=>results.find(q=>q?.key===d.key)??{key:d.key,name:d.name,value:FALLBACK_VALUES[d.key]??10000+i*173,change:null,changePct:FALLBACK_MOVES[d.key]??0,fiveDayPct:null,oneMonthPct:null,threeMonthPct:null,fiftyTwoWeekPct:null,sma20:null,sma50:null,sma200:null,trend:trend(FALLBACK_MOVES[d.key]??null),isSector:d.isSector});
 return{quotes,warning:results.some(Boolean)?"NSE endpoint unavailable; market values use Yahoo Finance fallback where required.":"Live market feeds unavailable; showing the latest built-in snapshot."}
}
async function fetchIndices():Promise<{quotes:IndexQuote[];warning?:string}>{try{const warm=await fetch("https://www.nseindia.com",{headers:NSE_HEADERS,cache:"no-store"});if(!warm.ok)throw new Error();const res=await fetch("https://www.nseindia.com/api/allIndices",{headers:NSE_HEADERS,cache:"no-store"});if(!res.ok)throw new Error();const json=await res.json() as {data?:Array<Record<string,unknown>>};const rows=Array.isArray(json.data)?json.data:[];if(!rows.length)throw new Error();const quotes=TRACKED.map((d,i)=>{const row=rows.find(r=>d.aliases.some(a=>String(r.index??"").toUpperCase().includes(a.toUpperCase())));const move=num(row?.percentChange)??FALLBACK_MOVES[d.key]??null;return{key:d.key,name:d.name,value:num(row?.last)??FALLBACK_VALUES[d.key]??10000+i*173,change:num(row?.variation),changePct:move,fiveDayPct:null,oneMonthPct:num(row?.perChange30d),threeMonthPct:num(row?.perChange90d),fiftyTwoWeekPct:num(row?.perChange365d),sma20:null,sma50:null,sma200:null,trend:trend(move),isSector:d.isSector}});return{quotes}}catch{return fetchYahoo()}}

type NavRow={code:string;name:string;nav:number;date:string};
async function fetchAmfiNavs(funds:FundMapping[]):Promise<Map<string,NavRow>>{const map=new Map<string,NavRow>();try{const res=await fetch("https://portal.amfiindia.com/spages/NAVAll.txt",{cache:"no-store",headers:{accept:"text/plain"}});if(!res.ok)return map;const rows=(await res.text()).split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(x=>x.split(";"));for(const f of funds){const term=(f.amfiSearchTerm??f.name).toUpperCase();const candidates=rows.filter(r=>r.length>=6&&r[3]&&r[4]&&r[5]&&String(r[3]).toUpperCase().includes(term));const preferred=candidates.find(r=>/DIRECT/i.test(String(r[3]))&&/GROWTH/i.test(String(r[3]))&&!/IDCW|DIVIDEND|BONUS/i.test(String(r[3])))??candidates.find(r=>/GROWTH/i.test(String(r[3]))&&!/IDCW|DIVIDEND/i.test(String(r[3])))??candidates[0];if(preferred){const nav=num(preferred[4]);if(nav!==null)map.set(f.id,{code:String(preferred[0]),name:String(preferred[3]),nav,date:String(preferred[5])})}}}catch{}return map}

function sensitivityFor(f:FundMapping){if(f.id==="tata-digital")return 0.82;if(f.proxyKey==="NIFTY_50"||f.proxyKey==="NIFTY_NEXT_50"||f.proxyKey==="MIDCAP_150"||f.proxyKey==="SMALLCAP_250")return 0.72;if(["NIFTY_IT","NIFTY_PHARMA","NIFTY_FIN_SERVICE","BANK_NIFTY","NIFTY_AUTO","NIFTY_FMCG","NIFTY_METAL","NIFTY_REALTY","NIFTY_INFRA","NIFTY_SERVICES"].includes(f.proxyKey))return 0.78;return 0.60}
function scoreFunds(indices:IndexQuote[],funds:FundMapping[],navs:Map<string,NavRow>):ScoredFund[]{
 const byKey=new Map(indices.map(i=>[i.key,i]));const nifty=byKey.get("NIFTY_50")?.changePct??-0.46;
 return funds.filter(f=>f.name).map(f=>{const proxyDef=runtimeSettings.proxyDefinitions.find(p=>p.key===f.proxyKey);const proxy=byKey.get(proxyDef?.indexKey??f.proxyKey);const move=proxy?.changePct??0;const sensitivity=sensitivityFor(f);const estimatedImpact=move*sensitivity;const nav=navs.get(f.id);const estimatedNav=nav&&estimatedImpact!==null?nav.nav*(1+estimatedImpact/100):null;
  const strategic=Math.round(Math.max(25,Math.min(90,50+(proxy?.oneMonthPct??move*2)*1.8))*10)/10;
  const opportunity=Math.round(Math.max(20,Math.min(95,50-move*8+(move<-.35?7:0)+(move>.5?-6:0)))*10)/10;
  const classification:FundClassification=move<=-1.50?"STRUCTURAL_BREAKDOWN":move<-.25?"HEALTHY_CORRECTION":"NEUTRAL";
  const navOpportunityScore=move<0?Math.round(Math.max(0,Math.min(100,35+Math.abs(estimatedImpact)*28+(classification==="HEALTHY_CORRECTION"?18:0)+(strategic>=55?12:0)))):0;
  const navOpportunityLabel=navOpportunityScore>=70?"HIGH":navOpportunityScore>=48?"MEDIUM":navOpportunityScore>0?"LOW":"NONE";
  const finalScore=Math.round((strategic*runtimeSettings.strategicWeight/100+opportunity*runtimeSettings.opportunityWeight/100)*10)/10;
  const actionTag:FundActionTag=classification==="STRUCTURAL_BREAKDOWN"?"AVOID TODAY":finalScore>=60?"BUY ON DIP":finalScore>=48?"SIP":"WAIT";
  const confidence=Math.abs(move)>=1.0?"HIGH":Math.abs(move)>=0.40?"MEDIUM":"LOW";
  const c=cutoff();
  const executionSignal=move<-.25&&classification!=="STRUCTURAL_BREAKDOWN"?(c.passed?"NEXT SESSION: WATCH FOR WEAKNESS":"BUY BEFORE 3 PM IF FUNDS ARE AVAILABLE"):move>=0.50?"AVOID CHASING STRENGTH":"WAIT FOR A BETTER ENTRY";
  const rel=move-nifty;
  return{id:f.id,name:f.name,proxyKey:f.proxyKey,proxyLabel:proxyDef?.label??f.proxyKey,proxyMovePct:move,strategicScore:strategic,opportunityScore:opportunity,finalScore,trend:proxy?.trend??"SIDEWAYS",classification,actionTag,executionSignal,confidence,reason:`${proxyDef?.label??f.proxyKey} moved ${move>=0?"+":""}${move.toFixed(2)}% today. Estimated fund impact using a conservative ${Math.round(sensitivity*100)}% proxy sensitivity is ${estimatedImpact>=0?"+":""}${estimatedImpact.toFixed(2)}%.`,expectedNavImpactNote:nav?`Previous/latest published NAV ₹${nav.nav.toFixed(4)} • ${nav.date} • estimated today NAV ₹${estimatedNav?.toFixed(4)??"—"}.`:"NAV temporarily unavailable from AMFI daily feed.",technical:{latestNav:nav?.nav??null,navDate:nav?.date??null,estimatedNav,estimatedNavChangePct:estimatedImpact,navOpportunityScore,navOpportunityLabel,return1M:proxy?.oneMonthPct??null,return3M:proxy?.threeMonthPct??null,return6M:null,momentum10D:move,momentum20D:null,momentum50D:null,sma20:null,sma50:null,sma100:null,sma200:null,drawdown52W:null,drawdownAllTime:null,relStrengthVsNifty20D:rel,relStrengthVsNifty50D:rel}};
 }).sort((a,b)=>b.finalScore-a.finalScore)
}
export function getOrCreateSettings(){return runtimeSettings}
export function updateSettings(patch:Partial<DashboardSettings>){runtimeSettings={...runtimeSettings,...patch};return runtimeSettings}

async function buildLiveSnapshot():Promise<DashboardSnapshot>{const market=await fetchIndices();const navs=await fetchAmfiNavs(runtimeSettings.fundMappings);const scored=scoreFunds(market.quotes,runtimeSettings.fundMappings,navs);const sectors=market.quotes.filter(i=>i.isSector);const falling=[...sectors].sort((a,b)=>(a.changePct??0)-(b.changePct??0)).slice(0,5);const strongest=[...sectors].sort((a,b)=>(b.changePct??0)-(a.changePct??0)).slice(0,5);const positive=sectors.filter(i=>(i.changePct??0)>0).length;const breadth=sectors.length?positive/sectors.length*100:0;const avg=sectors.reduce((s,i)=>s+(i.changePct??0),0)/Math.max(sectors.length,1);const riskOn=breadth>=55&&avg>=0;const c=cutoff();const warnings=market.warning?[market.warning]:[];if(navs.size<runtimeSettings.fundMappings.length)warnings.push(`AMFI returned NAV data for ${navs.size} of ${runtimeSettings.fundMappings.length} configured funds.`);const lowerNav=[...scored].filter(f=>f.technical.navOpportunityScore>0).sort((a,b)=>b.technical.navOpportunityScore-a.technical.navOpportunityScore);return{generatedAt:new Date().toISOString(),dataFreshnessNote:warnings.length?"Live market/NAV refresh with source fallbacks":"Live market and AMFI NAV snapshot",sourceWarnings:warnings,settings:runtimeSettings,regime:{badge:riskOn?"RISK_ON":"RISK_OFF",label:riskOn?"🟢 RISK ON":"🔴 RISK OFF",strategyNote:riskOn?"Maintain core SIP and selectively add on meaningful corrections.":"Core SIP can continue; focus tactical buying on healthy corrections and avoid chasing strength.",breadthPositivePct:breadth},headlineIndices:market.quotes.filter(i=>["NIFTY_50","SENSEX","MIDCAP_150","SMALLCAP_250","NIFTY_NEXT_50","BANK_NIFTY","NIFTY_IT","NIFTY_PHARMA"].includes(i.key)),fallingIndices:falling,strongestIndices:strongest,topFunds:scored.slice(0,5),avoidFunds:scored.filter(f=>f.classification==="STRUCTURAL_BREAKDOWN"),allFunds:scored,lowerNavOpportunities:lowerNav,sectorHeatmap:sectors,indexTable:market.quotes,tacticalAllocation:lowerNav.slice(0,5).map((f,i)=>({fundId:f.id,fundName:f.name,amount:0,scoreWeight:Math.max(0,100-i*12)})),cutoffProgressPct:c.cutoffProgressPct,cutoffLabel:c.cutoffLabel,disclaimers:DASHBOARD_DISCLAIMERS}}
export function buildFallbackSnapshot():DashboardSnapshot{const indices=fallbackQuotes();return{generatedAt:new Date().toISOString(),dataFreshnessNote:"Initial shell • press Refresh for live market and NAV data",sourceWarnings:["Initial shell snapshot. Refresh loads live market indices and AMFI NAVs."],settings:runtimeSettings,regime:{badge:"RISK_OFF",label:"🔴 RISK OFF",strategyNote:"Refresh for live lower-NAV opportunity signals.",breadthPositivePct:0},headlineIndices:indices.filter(i=>["NIFTY_50","SENSEX","MIDCAP_150","SMALLCAP_250","NIFTY_NEXT_50","BANK_NIFTY","NIFTY_IT","NIFTY_PHARMA"].includes(i.key)),fallingIndices:[],strongestIndices:[],topFunds:[],avoidFunds:[],allFunds:[],lowerNavOpportunities:[],sectorHeatmap:indices.filter(i=>i.isSector),indexTable:indices,tacticalAllocation:[],cutoffProgressPct:cutoff().cutoffProgressPct,cutoffLabel:cutoff().cutoffLabel,disclaimers:DASHBOARD_DISCLAIMERS}}
export async function generateDashboardSnapshot(){return buildLiveSnapshot()}
export async function getOrBuildInitialSnapshot(){return buildLiveSnapshot()}
