"use client";
import { useMemo, useState } from "react";
import type { DashboardSnapshot, IndexQuote, ScoredFund } from "@/lib/dashboard-types";

type Props={initialSnapshot:DashboardSnapshot};
const pct=(v:number|null)=>v===null?"—":`${v>=0?"+":""}${v.toFixed(2)}%`;
const money=(v:number|null)=>v===null?"—":`₹${v.toFixed(4)}`;
const num=(v:number|null)=>v===null?"—":v.toLocaleString("en-IN",{maximumFractionDigits:2});
const moveClass=(v:number|null)=>v===null?"muted":v>0?"positive":v<0?"negative":"muted";
const actionClass=(a:string)=>a==="BUY ON DIP"?"buy":a==="SIP"?"sip":a==="AVOID TODAY"?"avoid":"wait";
const navClass=(f:ScoredFund)=>f.technical.estimatedNavChangePct!==null&&f.technical.estimatedNavChangePct<0?"nav-drop":"nav-flat";
function IndexCard({idx}:{idx:IndexQuote}){return <article className="index-card"><div className="index-card-top"><span>{idx.name}</span><span className={moveClass(idx.changePct)}>{pct(idx.changePct)}</span></div><div className="index-value">{num(idx.value)}</div><div className="index-meta"><span>5D {pct(idx.fiveDayPct)}</span><span>1M {pct(idx.oneMonthPct)}</span><span className="trend">{idx.trend}</span></div></article>}
function OpportunityCard({f,n}:{f:ScoredFund;n:number}){return <article className={`opportunity-card ${navClass(f)}`}><div className="opportunity-rank">#{n+1}</div><div className="opportunity-main"><div className="opp-head"><div><div className="opp-name">{f.name}</div><div className="opp-proxy">{f.proxyLabel}</div></div><span className={`opportunity-badge ${f.technical.navOpportunityLabel.toLowerCase()}`}>{f.technical.navOpportunityLabel} OPPORTUNITY</span></div><div className="opp-numbers"><div><span>Sector / proxy today</span><strong className={moveClass(f.proxyMovePct)}>{pct(f.proxyMovePct)}</strong></div><div><span>Estimated fund impact</span><strong className={moveClass(f.technical.estimatedNavChangePct)}>{pct(f.technical.estimatedNavChangePct)}</strong></div><div><span>Modelled closing NAV</span><strong>{money(f.technical.estimatedNav)}</strong></div></div><div className="opp-footer"><span>Previous NAV {money(f.technical.latestNav)}</span><span>Confidence <b>{f.confidence}</b></span><span className={`decision ${actionClass(f.actionTag)}`}>{f.actionTag}</span></div><div className="execution-line">⏱ {f.executionSignal}</div></div></article>}

export default function DashboardClient({initialSnapshot}:Props){
 const [snapshot,setSnapshot]=useState(initialSnapshot);const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);const [tab,setTab]=useState<"opportunities"|"funds"|"indices">("opportunities");
 const lastUpdated=useMemo(()=>new Date(snapshot.generatedAt).toLocaleTimeString("en-IN",{hour12:false}),[snapshot.generatedAt]);
 const isLiveWindow=snapshot.cutoffProgressPct>0&&snapshot.cutoffProgressPct<100;
 const opportunityPeriod=isLiveWindow?"Today's":"Latest Session's";
 async function refresh(){setLoading(true);setError(null);try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);const res=await fetch("/api/dashboard/refresh",{signal:controller.signal,cache:"no-store"});clearTimeout(timer);const data=await res.json();if(!res.ok||!data.ok||!data.snapshot)throw new Error(data.error||"Refresh failed");setSnapshot(data.snapshot)}catch(e){setError(e instanceof Error?e.message:"Unable to refresh")}finally{setLoading(false)}}
 return <main className="terminal-shell">
  <header className="terminal-header"><div><div className="eyebrow">SMART MF • INDIA • DAILY NAV INTELLIGENCE</div><h1>Smart MF Daily Decision Terminal</h1><p>Find funds whose underlying market is weak — then estimate the potential lower same-day closing NAV without using stale or unverified market values.</p></div><div className="header-actions"><div className="freshness"><span className="live-dot"/> Updated {lastUpdated}</div><button onClick={refresh} disabled={loading} className="refresh-btn">{loading?"Refreshing…":"↻ Refresh Live Data"}</button></div></header>
  {snapshot.sourceWarnings.length>0&&<div className="source-banner"><b>Data status:</b> {snapshot.sourceWarnings.join(" • ")}</div>}{error&&<div className="error-banner">{error}</div>}

  <section className={`regime-banner ${snapshot.regime.badge.toLowerCase()}`}><div><span className="regime-label">{snapshot.regime.label}</span><div className="regime-note">{snapshot.regime.strategyNote}</div></div><div className="breadth"><span>Sector breadth</span><strong>{snapshot.regime.breadthPositivePct.toFixed(1)}%</strong><small>verified sectors positive</small></div></section>

  <section className="section-block hero-opportunity"><div className="section-heading"><div><span className="section-kicker">PRIMARY DECISION SCREEN</span><h2>🔥 {opportunityPeriod} Lower-NAV Opportunities</h2><p className="section-subtitle">Negative sector movement → estimated fund impact → potential lower closing NAV. Recommendations are shown only when both market and NAV inputs are verified. Outside market hours this shows the latest completed session, not a live intraday signal.</p></div><span className="section-note">Ranked by validated NAV opportunity score</span></div>{snapshot.lowerNavOpportunities.length?<div className="opportunity-list">{snapshot.lowerNavOpportunities.slice(0,6).map((f,n)=><OpportunityCard key={f.id} f={f} n={n}/>)}</div>:<div className="empty-state">No validated lower-NAV opportunity detected right now. If data is unverified, the dashboard intentionally suppresses tactical BUY signals rather than using stale values.</div>}</section>

  <section className="cutoff-strip"><div><span className="section-kicker">EXECUTION WINDOW</span><strong>{snapshot.cutoffLabel}</strong><small>For same-day NAV applicability, the purchase must satisfy the applicable scheme cut-off and funds-realisation conditions. The dashboard does not treat 3:00 PM alone as a guarantee.</small></div><div className="cutoff-meter"><div className="progress"><div style={{width:`${Math.min(snapshot.cutoffProgressPct,100)}%`}}/></div><span>{snapshot.cutoffProgressPct.toFixed(0)}%</span></div></section>

  <section className="section-block"><div className="section-heading"><div><span className="section-kicker">MARKET OVERVIEW</span><h2>Main NIFTY Indices</h2></div><span className="section-note">Validated market snapshot</span></div><div className="index-grid">{snapshot.headlineIndices.map(i=><IndexCard key={i.key} idx={i}/>)}</div></section>

  <section className="two-col"><div className="panel"><div className="panel-title"><h3>Largest Sector Declines</h3><span>{opportunityPeriod.replace("'s","")}</span></div>{snapshot.fallingIndices.map(i=><div className="rank-row" key={i.key}><span>{i.name}</span><b className="negative">{pct(i.changePct)}</b></div>)}</div><div className="panel"><div className="panel-title"><h3>Strongest Sectors</h3><span>{opportunityPeriod.replace("'s","")}</span></div>{snapshot.strongestIndices.map(i=><div className="rank-row" key={i.key}><span>{i.name}</span><b className={moveClass(i.changePct)}>{pct(i.changePct)}</b></div>)}</div></section>

  <section className="section-block"><div className="section-heading"><div><span className="section-kicker">RESEARCH TERMINAL</span><h2>Funds, NAV & Market Map</h2></div><div className="tabs"><button className={tab==="opportunities"?"active":""} onClick={()=>setTab("opportunities")}>Lower NAV</button><button className={tab==="funds"?"active":""} onClick={()=>setTab("funds")}>All Funds</button><button className={tab==="indices"?"active":""} onClick={()=>setTab("indices")}>Indices</button></div></div>
   {tab==="opportunities"?<div className="fund-table-wrap"><table className="fund-table"><thead><tr><th>Fund</th><th>Latest NAV</th><th>Modelled NAV</th><th>Est. Impact</th><th>Proxy Today</th><th>Opportunity</th><th>Action</th></tr></thead><tbody>{snapshot.allFunds.map(f=><tr key={f.id}><td><strong>{f.name}</strong><small>{f.proxyLabel}</small></td><td className="nav">{money(f.technical.latestNav)}</td><td className="nav-drop-cell">{money(f.technical.estimatedNav)}</td><td className={moveClass(f.technical.estimatedNavChangePct)}>{pct(f.technical.estimatedNavChangePct)}</td><td className={moveClass(f.proxyMovePct)}>{pct(f.proxyMovePct)}</td><td><span className={`opportunity-mini ${f.technical.navOpportunityLabel.toLowerCase()}`}>{f.technical.navOpportunityScore}/100</span></td><td><span className={`decision ${actionClass(f.actionTag)}`}>{f.actionTag}</span></td></tr>)}</tbody></table></div>:tab==="funds"?<div className="fund-table-wrap"><table className="fund-table"><thead><tr><th>Fund</th><th>NAV</th><th>NAV Date</th><th>Proxy</th><th>Today</th><th>Strategic</th><th>Opportunity</th><th>Final</th><th>Action</th></tr></thead><tbody>{snapshot.allFunds.map(f=><tr key={f.id}><td><strong>{f.name}</strong></td><td className="nav">{money(f.technical.latestNav)}</td><td>{f.technical.navDate??"—"}</td><td>{f.proxyLabel}</td><td className={moveClass(f.proxyMovePct)}>{pct(f.proxyMovePct)}</td><td>{f.strategicScore}</td><td>{f.opportunityScore}</td><td><span className="score">{f.finalScore.toFixed(1)}</span></td><td><span className={`decision ${actionClass(f.actionTag)}`}>{f.actionTag}</span></td></tr>)}</tbody></table></div>:<div className="fund-table-wrap"><table className="fund-table"><thead><tr><th>Index</th><th>Today</th><th>5D</th><th>1M</th><th>3M</th><th>52W</th><th>Trend</th></tr></thead><tbody>{snapshot.indexTable.map(i=><tr key={i.key}><td><strong>{i.name}</strong></td><td className={moveClass(i.changePct)}>{pct(i.changePct)}</td><td>{pct(i.fiveDayPct)}</td><td>{pct(i.oneMonthPct)}</td><td>{pct(i.threeMonthPct)}</td><td>{pct(i.fiftyTwoWeekPct)}</td><td>{i.trend}</td></tr>)}</tbody></table></div>}
  </section>

  <section className="section-block"><div className="section-heading"><div><span className="section-kicker">SECTOR ROTATION</span><h2>Sector Heatmap</h2></div><span className="section-note">Missing data is shown as unverified, never as positive/negative</span></div><div className="heatmap">{snapshot.sectorHeatmap.map(i=><div key={i.key} className={`heat-cell ${i.changePct===null?"missing":i.changePct>=0?"up":"down"}`}><span>{i.name.replace("NIFTY ","")}</span><strong>{i.changePct===null?"UNVERIFIED":pct(i.changePct)}</strong></div>)}</div></section>
  <section className="section-block methodology"><div><span className="section-kicker">HOW THE SIGNAL WORKS</span><h2>Lower-NAV Opportunity Engine</h2><div className="method-grid"><div><b>01 · Validate data</b><span>Reject abnormal or stale market values before scoring.</span></div><div><b>02 · Map the fund</b><span>Connect each fund to its configured market proxy.</span></div><div><b>03 · Detect weakness</b><span>Find validated sectors/indices falling in the latest completed session or live session.</span></div><div><b>04 · Estimate impact</b><span>Apply a conservative proxy sensitivity to model a closing NAV.</span></div><div><b>05 · Verify NAV</b><span>Use the latest published AMFI NAV, with exact scheme-code overrides where required.</span></div><div><b>06 · Execute correctly</b><span>Only show a same-day execution message during the 9:15 AM–3:00 PM window and only when the inputs are verified.</span></div></div></div></section>
  <footer className="terminal-footer"><div><b>Smart MF Daily Decision Terminal</b><span>Decision support only • modelled NAV is not a guaranteed NAV.</span></div><div>AMFI NAV + validated market proxy data • proxy sensitivity is an approximation • verify applicable cut-off, scheme rules and funds-realisation requirements before investing.</div></footer>
 </main>;
}
